// Design/components/surfaces/Tabs.jsx
import React from "react";

export function Tabs({ tabs = [], active, onChange }) {
  return (
    <div style={{ display: "flex", gap: "4px", background: "var(--neutral-100)", padding: "4px", borderRadius: "var(--radius-md)", fontFamily: "var(--font-body)" }}>
      {tabs.map((t) => {
        const isActive = t.value === active;
        return (
          <button
            key={t.value}
            onClick={() => onChange && onChange(t.value)}
            style={{
              flex: 1,
              border: "none",
              padding: "8px 16px",
              borderRadius: "var(--radius-sm)",
              background: isActive ? "var(--color-surface)" : "transparent",
              color: isActive ? "var(--color-primary)" : "var(--color-text-secondary)",
              boxShadow: isActive ? "var(--shadow-xs)" : "none",
              font: "var(--text-label)",
              cursor: "pointer",
              transition: "background var(--duration-fast) var(--ease-standard)",
            }}
          >
            {t.label}
          </button>
        );
      })}
    </div>
  );
}

// App/src/lib/components/Tabs.svelte
<script lang="ts">
  type Tab = { value: string; label: string };

  let { tabs = [], active = $bindable('') }: { tabs?: Tab[]; active?: string } = $props();

  function select(value: string) {
    active = value;
  }
</script>

<div class="flex gap-1 rounded-md bg-surface-sunken p-1" role="tablist">
  {#each tabs as tab}
    <button
      type="button"
      role="tab"
      aria-selected={active === tab.value}
      class="flex-1 rounded-sm px-3 py-2 text-sm font-semibold transition {active === tab.value
        ? 'bg-surface text-ink shadow-xs'
        : 'text-ink-secondary hover:text-ink'}"
      onclick={() => select(tab.value)}
    >
      {tab.label}
    </button>
  {/each}
</div>
