// App/src/lib/components/Avatar.svelte
<script lang="ts">
  let {
    initials = '??',
    size = 48,
    status = null,
    src = null,
    alt = ''
  }: {
    initials?: string;
    size?: number;
    status?: 'online' | 'offline' | null;
    /** A profile photo, if there is one. Initials are the fallback, not the default. */
    src?: string | null;
    alt?: string;
  } = $props();
</script>

<div class="relative shrink-0" style="width:{size}px;height:{size}px">
  {#if src}
    <img {src} {alt} class="h-full w-full rounded-full object-cover" />
  {:else}
    <div
      class="flex h-full w-full items-center justify-center rounded-full bg-primary-subtle text-sm font-semibold text-primary"
    >
      {initials}
    </div>
  {/if}
  {#if status === 'online'}
    <span
      class="absolute bottom-0 right-0 h-3 w-3 rounded-full border-2 border-surface bg-success"
    ></span>
  {/if}
</div>

// Design/components/surfaces/Avatar.jsx
import React from "react";

export function Avatar({ src, initials = "?", size = 40, status }) {
  const statusColor = { online: "var(--color-success)", busy: "var(--color-warning)", offline: "var(--neutral-400)" }[status];
  return (
    <span style={{ position: "relative", display: "inline-flex", width: size, height: size, flexShrink: 0 }}>
      {src ? (
        <img
          src={src}
          alt=""
          style={{ width: size, height: size, borderRadius: "var(--radius-full)", objectFit: "cover" }}
        />
      ) : (
        <span
          style={{
            width: size,
            height: size,
            borderRadius: "var(--radius-full)",
            background: "var(--color-primary-subtle)",
            color: "var(--color-primary)",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            font: "var(--weight-semibold) " + Math.round(size * 0.4) + "px var(--font-display)",
          }}
        >
          {initials}
        </span>
      )}
      {status && (
        <span
          style={{
            position: "absolute",
            bottom: 0,
            right: 0,
            width: size * 0.28,
            height: size * 0.28,
            borderRadius: "var(--radius-full)",
            background: statusColor,
            border: "2px solid var(--color-surface)",
          }}
        />
      )}
    </span>
  );
}
